### ISSUE TITLE
[feature] better cli progress indicator

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#528]
*Motivation*

Running checkup on a large project the spinner becomes unresponsive and there is no way to tell what is happening.
```
  checkup:checkup-plugin-ember:hooks:register-tasks done +9s
  checkup:meta-task start ProjectMetaTask run +0ms
  checkup:meta-task start CheckupMetaTask run +74ms
  checkup:meta-task CheckupMetaTask run done +2ms
Checking up on your project... ⣻
```

A really good example of a cli progress indicator showing really helpful information is https://github.com/stefanpenner/ember-cli-progress.

**Comment by scalvert** [comment]
It's a reasonable suggestion, but we're leveraging oclif's built-in progress indicator. We're doing our best not to deviate too much from their standards so that we can focus on building the functionality we care about and not reinventing the wheel. This makes upgrades/additions much easier as we don't have to worry about any potential breakages etc. 

I think if we want to change this, we should potentially try to contribute something back to oclif such that we can provide a custom progress indicator. Thoughts?

**Comment by scalvert** [comment]
I'm going to close this for now, @gabrielcsapo. Let me know if you want to revisit.
