### ISSUE TITLE
[question] make default info task optional

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#632]
The default task that outputs the following information:

> https://github.com/checkupjs/checkup/blob/e1b8ec5dcec8035e85c0f304b61ee59c3d7586a1/packages/cli/src/tasks/project-meta-task.ts

<img width="792" alt="Screen Shot 2020-08-11 at 11 54 43 AM" src="https://user-images.githubusercontent.com/1854811/89937177-97ce2380-dbc9-11ea-8aff-9025a5ccb233.png">

makes it hard to debug what files are being processed since this task processes them all. 

Maybe having processed files be at a per task level would make tasks easier to debug.

**Comment by scalvert** [comment]
The default task [doesn't process all files](https://github.com/checkupjs/checkup/blob/master/packages/cli/src/tasks/project-meta-task.ts#L39). There's up-front lookup that checkup does to expand the globs into a consistent format, which are subsequently used in filtering for all other tasks. This would happen regardless of whether the default info task runs. 

There's some minimum info we want to publish in checkup, regardless of the task run. It helps add context to the tasks that were run, and provide some necessary information for debugging a task run when running in a disconnected environment, such as CI. Specifically, we specify the checkup version, config, flags, etc so that you can reproduce the same run locally if you need to debug. I believe this information should continue to be produced for all task executions, regardless of the number of tasks run.

I hope this makes sense.
