### ISSUE TITLE
SARIF refactor (specifically to enable diagnostics)

### ISSUE THREAD

**Issue by carakessler** [checkupjs/checkup#869]
To enable more verbose info in the SARIF log (to be consumed by the VSCode SARIF viewer), we need to do some refactoring of where we are storing certain pieces of data.

Currently, we use SARIF's `ruleId` to store the name of a Task. If we want to allow for more specific messaging from SARIF and specifically unlock the ability to leverage the diagnostic feature in VSCode, we need to allow for `ruleId` to be used to map to a specific type of result, rather than a way to group all results coming from a particular Task. Since `ruleId` is an optional property anyway, we are now going to only define it when it is needed as a key a specific diagnostic, and will just store the task name under `properties.taskName`.

**Comment by carakessler** [comment]
@scalvert I can do this refactor, but wanted to verify that what I listed above is all that needs to be done in terms of backwards incompatible changes to the way we are using SARIF

**Comment by carakessler** [comment]
@scalvert huge con with this - the SARIF extension groups results by `ruleId` (which is currently taskName) which is why all results from a given Task are grouped in the UX of the extension. I don't know that the ability to use diagnostics (which will be a major power user thing) outweighs the niceness of how the SARIF extension UX looks now and having results from the same Task grouped together there

**Comment by scalvert** [comment]
Let me break down the intent/priorities of this refactor:

1. Providing lower-level APIs such that you can build a raw `Sarif.Result` using all available properties.
2. Compose higher-level utils/helpers that build `Sarif.Result` instances using our common task data types (Lint results, file list results, etc)
3. Provide more specific annotation in the vscode Sarif viewer such that the ruleId, rule name, rule description, kind, etc are more accurate.
4. Provide the ability for SARIF results to contain additional metadata per ruleId in order to better integrate with vscode's `Diagnostic`, allowing for tighter, more useful integrations with the editor.

I believe if we approach the refactor from 1 down, we can determine the best course of action as we proceed. Does this make sense?

**Comment by scalvert** [comment]
We've synced up and have began a partnership with the folks who work on the SARIF SDK at Microsoft. We're collaborating on a new [JS SDK for SARIF](https://github.com/microsoft/sarif-js-sdk), and will likely move further development related to building SARIF logs there.
